export { PokemonService } from './lib/pokemon/pokemon.service';
export { Pokemon } from './lib/pokemon/pokemon.model';
export { PokemonMeta } from './lib/pokemon/pokemon-meta.model';
export { StarshipsService } from './lib/starships/starships.service';
export { Starships } from './lib/starships/starships.model';
export { BooksService } from './lib/books/books.service';
export { Books } from './lib/books/books.model';
export { YoutubeService } from './lib/youtube/youtube.service';
export { Youtube } from './lib/youtube/youtube.model';
export { SpotifyService } from './lib/spotify/spotify.service';
export { Spotify } from './lib/spotify/spotify.model';
export { GuildService } from './lib/guild/guild.service';
export { Guild } from './lib/guild/guild.model';
export { AirService } from './lib/air/air.service';
export { Air } from './lib/air/air.model';
export { EmpiresService } from './lib/empires/empires.service';
export { Empires } from './lib/empires/empires.model';
export { RocketsService } from './lib/rockets/rockets.service';
export { Rockets } from './lib/rockets/rockets.model';

export { CoreDataModule } from './lib/core-data.module' ;
export { TokenInterceptor } from './lib/auth/token-interceptor.service';